version: "2.4"
services:
  web:
    build: ./nginx
    ports:
      - "8080:8080"
    volumes:
      - sharedVol:/var/www/api/.wb_generator
        #- filesVol:/var/www/files
      - /home/kaname/SSTIC/chall2021/nginx_files:/var/www/files
    cap_drop:
      - ALL
    restart: always
    cpu_count: 1
    cpus: '1'
    mem_limit: 200M
  build:
    build: ./whitebox_builder
    # set the key after -k
    # set the time between two compile after -t
    # set the suffix after -s
    command: ["-k", "8899aabbccddeeff0011223344556677", "-t", "900", "-s", "0011223344556677"]
    volumes:
      - sharedVol:/home/docker-user/out
    cap_drop:
      - ALL
    network_mode: "none"
    restart: always
    cpu_count: 1
    cpus: '0.50'
    mem_limit: 250M
volumes:
  sharedVol: {}
  filesVol: {}

