version: "3"
services:
  web:
    build: ./nginx
    ports:
      - "8080:8080"
    volumes:
      - sharedVol:/var/www
    cap_drop:
      - ALL
  build:
    build: ./whitebox_builder
    # set the key after -k
    # set the time between two compile after -t
    # set the lower suffix after -s
    command: ["-k", "00000000000000000000000000000000", "-t", "5", "-s", "00000000"]
    volumes:
      - sharedVol:/home/docker-user/out
    cap_drop:
      - ALL
    network_mode: "none"
volumes:
  sharedVol: {}

